### ISSUE TITLE
Issue after Upgrade from 4.4.1 to 5.0.1

### ISSUE THREAD

**Issue by BReligion** [tavicu/homebridge-samsung-tizen#350]
First off great plugin! Love it. Some amazing work you are doing here.
I am fairly new to all of this and the whole homebridge community. I have searched the other issues and can't seem to find anything. So i apologize if i missed it and it's an obvious newby fix.

model: 17_KANTM_UHD
modelname: UN65MU8000

I upgraded to the latest release and when i start home bridge i get the following error and Home can no longer communicate to the TV. 
 [SamsungTizen] [(...Object.values(...).map(...)),(...Object.values(...).map(...))].flat is not a function
I have un uninstalled the plugin, removed everything from Homebridge and Homekit and started over and gotten the same result.

I have downgraded to v4.4.1 and was able to add back to HomeKit and now it's working as it was before.

I suspect it might have something to do with the version of Node.js? 
Like i said, I am fairly new to all of this.

Thanks!!

**Comment by tavicu** [comment]
Hi!

Yup, you suspect correctly :)

Update node.js to a newer version!

Flat function was introduced in node 11.0.0

**Comment by BReligion** [comment]
Perfect! I will try again tonight.
I have tried a couple of times to update Node.js, it didn't take and just rolled itself back to the version it's at now.

Thanks for the confirmation!
